export const projects = [
    {
      id: 1,
      crop: 'Wheat (Lokwan)',
      startDate: '2023-11-15',
      status: 'On Track',
      progress: 75,
      endDate: null,
      yield: null,
    },
    {
      id: 2,
      crop: 'Tomato (Desi)',
      startDate: '2024-01-20',
      status: 'Needs Attention',
      progress: 40,
      endDate: null,
      yield: null,
    },
    {
      id: 3,
      crop: 'Paddy (Basmati)',
      startDate: '2023-06-01',
      status: 'Completed',
      progress: 100,
      endDate: '2023-10-25',
      yield: '25 quintals',
    },
    {
        id: 4,
        crop: 'Soybean (Yellow)',
        startDate: '2023-07-10',
        status: 'Completed',
        progress: 100,
        endDate: '2023-11-05',
        yield: '12 quintals/acre',
    },
    {
      id: 5,
      crop: 'Mustard',
      startDate: '2024-03-01',
      status: 'Completed',
      progress: 100,
      endDate: '2024-06-15',
      yield: '8 quintals/acre',
  },
];
